<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\API\HomeController' shared autowired service.

include_once $this->targetDirs[3].'\\src\\API\\HomeController.php';

return $this->services['App\Controller\HomeController'] = new \App\Controller\HomeController();
