<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\API\ByIDFindsPurchaseOrder' shared autowired service.

include_once $this->targetDirs[3].'\\src\\API\\ByIDFindsPurchaseOrder.php';

return $this->services['App\Controller\ByIDFindsPurchaseOrder'] = new \App\Controller\ByIDFindsPurchaseOrder();
