<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\API\ByStatusReturnInventory' shared autowired service.

include_once $this->targetDirs[3].'\\src\\API\\ByStatusReturnInventory.php';

return $this->services['App\Controller\ByStatusReturnInventory'] = new \App\Controller\ByStatusReturnInventory();
