<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\API\ByIDDeletePurchaseOrder' shared autowired service.

include_once $this->targetDirs[3].'\\src\\API\\ByIDDeletePurchaseOrder.php';

return $this->services['App\Controller\ByIDDeletePurchaseOrder'] = new \App\Controller\ByIDDeletePurchaseOrder();
