<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\API\CreateUser' shared autowired service.

include_once $this->targetDirs[3].'\\src\\API\\CreateUser.php';

return $this->services['App\Controller\CreateUser'] = new \App\Controller\CreateUser();
