<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\API\DeletePet' shared autowired service.

include_once $this->targetDirs[3].'\\src\\API\\DeletePet.php';

return $this->services['App\Controller\DeletePet'] = new \App\Controller\DeletePet();
