<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\API\InStoreUpdatePet' shared autowired service.

include_once $this->targetDirs[3].'\\src\\API\\InStoreUpdatePet.php';

return $this->services['App\Controller\InStoreUpdatePet'] = new \App\Controller\InStoreUpdatePet();
