<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\API\LogOutUser' shared autowired service.

include_once $this->targetDirs[3].'\\src\\API\\LogOutUser.php';

return $this->services['App\Controller\LogOutUser'] = new \App\Controller\LogOutUser();
