<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\API\UpdateUser' shared autowired service.

include_once $this->targetDirs[3].'\\src\\API\\UpdateUser.php';

return $this->services['App\Controller\UpdateUser'] = new \App\Controller\UpdateUser();
