<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEw8a8UL\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEw8a8UL/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerEw8a8UL.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerEw8a8UL\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerEw8a8UL\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'Ew8a8UL',
    'container.build_id' => '1e607faa',
    'container.build_time' => 1524154915,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerEw8a8UL');
