<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXWe4IWy\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXWe4IWy/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerXWe4IWy.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerXWe4IWy\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerXWe4IWy\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'XWe4IWy',
    'container.build_id' => 'd2ae941d',
    'container.build_time' => 1524505935,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerXWe4IWy');
